def collect_employee_data(ui, employee_id, archived=0):
    employee_data = {
        "employee_id": employee_id,  # Include the generated ID
        "Archived": archived,
        "first_name": ui.FirstName.toPlainText(),
        "middle_name": ui.MiddleName.toPlainText(),
        "last_name": ui.SurName.toPlainText(),
        "position": ui.Position.toPlainText(),  # Ensure this field exists
        "dmg_address": ui.DumaAddress.toPlainText(),
        "home_address": ui.HomeAddress.toPlainText(),
        "date_of_birth": ui.DateOfBirth.toPlainText(),
        "place_of_birth": ui.PlaceOfBirth.toPlainText(),
        "citizenship": ui.Citizenship.toPlainText(),
        "passport_num": ui.NONFILIPINO_passport.toPlainText(),
        "acr_num": ui.NONFILIPINO_acrnum.toPlainText(),
        "passport_date_issued": ui.NONFILIPINO_dateissued.toPlainText(),
        "contact_num": ui.ContactNumber.toPlainText(),
        "email": ui.Email.toPlainText(),
        "tin": ui.TINnumber.toPlainText(),
        "sss": ui.SSSnumber.toPlainText(),
        "pagibig": ui.PagIbigNumber.toPlainText(),
        "philhealth": ui.PhilHNumber.toPlainText(),
        "church_affiliation": ui.ChurchAffiliation.toPlainText(),
        
        "father_firstname": ui.Father_FirstName.toPlainText(), 
        "father_lastname": ui.Father_LastName.toPlainText(), 
        "father_middle": ui.Father_MiddleName.toPlainText(), 
        "father_job": ui.FatherJob.toPlainText(),
        "father_address": ui.FatherAddress.toPlainText(),
        
        "mother_firstname": ui.Mother_FirstName.toPlainText(),
        "mother_lastname": ui.Mother_LastName.toPlainText(),
        "mother_middlename": ui.Mother_MiddleName.toPlainText(),
        
        "mother_job": ui.MotherJob.toPlainText(),
        "mother_address": ui.MotherAddress.toPlainText(),
        
        "sibling1_firstname": ui.sibling1_FirstName.toPlainText(),
        "sibling1_lastname": ui.sibling1_LastName.toPlainText(),
        "sibling1_middlename": ui.sibling1_MiddleName.toPlainText(),
        "sibling1_occupation": ui.sibling1_occupation.toPlainText(),
        "sibling1_address": ui.sibling1_address.toPlainText(),
        
        "sibling2_firstname": ui.sibling2_FirstName.toPlainText(),
        "sibling2_lastname": ui.sibling2_LastName.toPlainText(),
        "sibling2_middlename": ui.sibling2_MiddleName.toPlainText(),
        "sibling2_occupation": ui.sibling2_occupation.toPlainText(),
        "sibling2_address": ui.sibling2_address.toPlainText(),
        
        "civil_status": ui.CivilStatus.toPlainText(),
        
        "spouse_firstename": ui.Spouse_FirstName.toPlainText(),
        "spouse_middlename": ui.Spouse_MiddleName.toPlainText(),
        "spouse_lastname": ui.Spouse_LastName.toPlainText(),
        
        "place_of_marriage": ui.PlaceOfMarriage.toPlainText(),
        "date_of_marriage": ui.DateOfMarriage.toPlainText(),
        
        "child1_firstname": ui.child1_FirstName.toPlainText(),
        "child1_lastname": ui.child1_LastName.toPlainText(),
        "child1_middlename": ui.child1_MiddleName.toPlainText(),
        "child1_birthdate": ui.child1_dateofbirth.toPlainText(),
        
        "child2_firstname": ui.child2_FirstName.toPlainText(),
        "child2_lastname": ui.child2_LastName.toPlainText(),
        "child2_middlename": ui.child2_MiddleName.toPlainText(),
        "child2_birthdate": ui.child2_dateofbirth.toPlainText(),
        
        "elementary_school": ui.elementary_school.toPlainText(),
        "elementary_address": ui.elementary_school_address.toPlainText(),
        "elem_diploma": ui.diploma_elementary.toPlainText(),
        "elem_yeargraduated": ui.yeargraduate_elementary.toPlainText(),
        "highschool_name": ui.highschool.toPlainText(),
        "highschool_address": ui.address_highschool.toPlainText(),
        "highschool_diploma": ui.diploma_highschool.toPlainText(),
        "highschool_yeargraduated": ui.yeargraduate_highschool.toPlainText(),
        "college_school": ui.College.toPlainText(),
        "college_address": ui.address_college.toPlainText(),
        "college_diploma": ui.diploma_college.toPlainText(),
        "college_yeargraduated": ui.yeargraduate_college.toPlainText(),
        "graduate_school": ui.Graduateschool.toPlainText(),
        "graduate_address": ui.address_graduateschool.toPlainText(),
        "graduate_diploma": ui.diploma_graduateschool.toPlainText(),
        "graduate_yeargraduated": ui.yeargraduate_graduateschool.toPlainText(),
        
        "related_staff1_firstname": ui.staff_FirstName1.toPlainText(),
        "related_staff1_lastname": ui.staff_LastName1.toPlainText(),
        "related_staff1_middlename": ui.staff_MiddleName1.toPlainText(),
        "related_staff1_relationship": ui.staff_relationship2.toPlainText(),
        "related_staff1_position": ui.staff_position3.toPlainText(),
        
        "related_staff2_firstname": ui.staff_FirstName2.toPlainText(),
        "related_staff2_lastname": ui.staff_LastName2.toPlainText(),
        "related_staff2_middlename": ui.staff_MiddleName2.toPlainText(),
        "related_staff2_relationship": ui.staff_relationship2_2.toPlainText(),
        "related_staff2_position": ui.staff_position2.toPlainText(),
        
        "scholarship_awards": ui.scholarships_awards.toPlainText(),
        "publications": ui.publications.toPlainText(),
        "name_of_employer": ui.name_employer.toPlainText(),
        "position_workplace": ui.position_workplace.toPlainText(),
        "period_of_employment": ui.period_employment.toPlainText(),
        "reason_for_leaving": ui.reason.toPlainText(),
        "employer_address": ui.address_employment.toPlainText(),
        "government_examinations": ui.government_examination.toPlainText(),
        "government_rating": ui.government_rating.toPlainText(),
        "government_date": ui.government_date.toPlainText(),
        "government_place": ui.Government_place.toPlainText(),
        "criminal_case_name": ui.case_name.toPlainText(),
    }
    return employee_data
