# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'preview_templatebctlie.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QStatusBar,
    QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1433, 1080)
        MainWindow.setStyleSheet(u"color: black;\n"
"background-color: white;")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 30, 91, 81))
        self.label.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.label.setPixmap(QPixmap(u":/images/logo_silliman.png"))
        self.label.setScaledContents(True)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(150, 30, 161, 41))
        self.label_3.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.label_3.setPixmap(QPixmap(u":/images/title2_header1.png"))
        self.label_3.setScaledContents(False)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-10, 140, 1461, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, -10, 1451, 161))
        self.label_2.setPixmap(QPixmap(u":/images/background2_header.png"))
        self.label_2.setScaledContents(True)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 90, 271, 16))
        self.label_4.setPixmap(QPixmap(u":/images/title2_header2.png"))
        self.home_button = QPushButton(self.centralwidget)
        self.home_button.setObjectName(u"home_button")
        self.home_button.setGeometry(QRect(1250, 60, 41, 31))
        self.home_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.home_button.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        icon = QIcon()
        icon.addFile(u":/images/button_home.png", QSize(), QIcon.Normal, QIcon.Off)
        self.home_button.setIcon(icon)
        self.home_button.setIconSize(QSize(256, 256))
        self.logout_button = QPushButton(self.centralwidget)
        self.logout_button.setObjectName(u"logout_button")
        self.logout_button.setGeometry(QRect(1310, 60, 75, 24))
        self.logout_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.logout_button.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        icon1 = QIcon()
        icon1.addFile(u":/images/button_logout.png", QSize(), QIcon.Normal, QIcon.Off)
        self.logout_button.setIcon(icon1)
        self.logout_button.setIconSize(QSize(500, 500))
        self.breadcrumb_label = QLabel(self.centralwidget)
        self.breadcrumb_label.setObjectName(u"breadcrumb_label")
        self.breadcrumb_label.setGeometry(QRect(10, 160, 381, 31))
        self.breadcrumb_label.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.breadcrumb_label.setPixmap(QPixmap(u":/images/title2_header3.png"))
        self.home_button_2 = QPushButton(self.centralwidget)
        self.home_button_2.setObjectName(u"home_button_2")
        self.home_button_2.setGeometry(QRect(30, 1000, 41, 31))
        self.home_button_2.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.home_button_2.setIcon(icon)
        self.home_button_2.setIconSize(QSize(256, 256))
        self.logout_button_2 = QPushButton(self.centralwidget)
        self.logout_button_2.setObjectName(u"logout_button_2")
        self.logout_button_2.setGeometry(QRect(80, 1005, 75, 24))
        self.logout_button_2.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.logout_button_2.setIcon(icon1)
        self.logout_button_2.setIconSize(QSize(500, 500))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(1060, 1000, 361, 41))
        font = QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setPixmap(QPixmap(u":/images/title2_header2.png"))
        self.frame_header = QFrame(self.centralwidget)
        self.frame_header.setObjectName(u"frame_header")
        self.frame_header.setGeometry(QRect(10, 190, 1411, 801))
        self.frame_header.setStyleSheet(u"background-color: rgb(222, 222, 222);")
        self.frame_header.setFrameShape(QFrame.StyledPanel)
        self.frame_header.setFrameShadow(QFrame.Raised)
        self.Profile_pic = QGraphicsView(self.frame_header)
        self.Profile_pic.setObjectName(u"Profile_pic")
        self.Profile_pic.setGeometry(QRect(20, 20, 211, 181))
        self.Profile_pic.setStyleSheet(u"border: 1px solid black")
        self.employee_name = QLabel(self.frame_header)
        self.employee_name.setObjectName(u"employee_name")
        self.employee_name.setGeometry(QRect(250, 20, 188, 36))
        font1 = QFont()
        font1.setPointSize(20)
        font1.setBold(True)
        self.employee_name.setFont(font1)
        self.employee_position = QLabel(self.frame_header)
        self.employee_position.setObjectName(u"employee_position")
        self.employee_position.setGeometry(QRect(250, 60, 93, 28))
        font2 = QFont()
        font2.setPointSize(16)
        font2.setBold(True)
        self.employee_position.setFont(font2)
        self.employee_department = QLabel(self.frame_header)
        self.employee_department.setObjectName(u"employee_department")
        self.employee_department.setGeometry(QRect(250, 100, 266, 28))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setBold(False)
        self.employee_department.setFont(font3)
        self.employee_hired_date = QLabel(self.frame_header)
        self.employee_hired_date.setObjectName(u"employee_hired_date")
        self.employee_hired_date.setGeometry(QRect(250, 130, 213, 26))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(False)
        self.employee_hired_date.setFont(font4)
        self.edit_info_button = QPushButton(self.frame_header)
        self.edit_info_button.setObjectName(u"edit_info_button")
        self.edit_info_button.setGeometry(QRect(250, 170, 131, 16))
        self.edit_info_button.setCursor(QCursor(Qt.ArrowCursor))
        self.edit_info_button.setStyleSheet(u"border-radius: 5px;\n"
"\n"
"background-color: rgb(50, 50, 50);\n"
"color: white;\n"
"font-weight: bold;\n"
"")
        self.archive_button = QPushButton(self.frame_header)
        self.archive_button.setObjectName(u"archive_button")
        self.archive_button.setGeometry(QRect(400, 170, 101, 16))
        self.archive_button.setStyleSheet(u"border-radius: 5px;\n"
"\n"
"background-color: rgb(138, 138, 138);\n"
"color: white;\n"
"font-weight: bold;\n"
"")
        self.archive_button_2 = QPushButton(self.frame_header)
        self.archive_button_2.setObjectName(u"archive_button_2")
        self.archive_button_2.setGeometry(QRect(530, 170, 101, 16))
        self.archive_button_2.setStyleSheet(u"border-radius: 5px;\n"
"\n"
"background-color: rgb(68, 255, 0);\n"
"color: black;\n"
"font-weight: bold;\n"
"")
        self.employee_duma_address_header = QLabel(self.frame_header)
        self.employee_duma_address_header.setObjectName(u"employee_duma_address_header")
        self.employee_duma_address_header.setGeometry(QRect(20, 220, 161, 21))
        font5 = QFont()
        font5.setPointSize(12)
        font5.setBold(True)
        self.employee_duma_address_header.setFont(font5)
        self.employee_duma_address_data = QLabel(self.frame_header)
        self.employee_duma_address_data.setObjectName(u"employee_duma_address_data")
        self.employee_duma_address_data.setGeometry(QRect(20, 240, 341, 31))
        font6 = QFont()
        font6.setPointSize(12)
        font6.setBold(False)
        self.employee_duma_address_data.setFont(font6)
        self.employee_duma_address_province = QLabel(self.frame_header)
        self.employee_duma_address_province.setObjectName(u"employee_duma_address_province")
        self.employee_duma_address_province.setGeometry(QRect(20, 270, 341, 31))
        self.employee_duma_address_province.setFont(font6)
        self.employee_address_header = QLabel(self.frame_header)
        self.employee_address_header.setObjectName(u"employee_address_header")
        self.employee_address_header.setGeometry(QRect(20, 300, 161, 21))
        self.employee_address_header.setFont(font5)
        self.employee_address_data = QLabel(self.frame_header)
        self.employee_address_data.setObjectName(u"employee_address_data")
        self.employee_address_data.setGeometry(QRect(20, 320, 341, 31))
        self.employee_address_data.setFont(font6)
        self.employee_address_province = QLabel(self.frame_header)
        self.employee_address_province.setObjectName(u"employee_address_province")
        self.employee_address_province.setGeometry(QRect(20, 350, 341, 31))
        self.employee_address_province.setFont(font6)
        self.birthday_header = QLabel(self.frame_header)
        self.birthday_header.setObjectName(u"birthday_header")
        self.birthday_header.setGeometry(QRect(20, 390, 161, 21))
        self.birthday_header.setFont(font5)
        self.employee_birthday = QLabel(self.frame_header)
        self.employee_birthday.setObjectName(u"employee_birthday")
        self.employee_birthday.setGeometry(QRect(20, 410, 341, 31))
        self.employee_birthday.setFont(font6)
        self.citz_header = QLabel(self.frame_header)
        self.citz_header.setObjectName(u"citz_header")
        self.citz_header.setGeometry(QRect(20, 440, 161, 21))
        self.citz_header.setFont(font5)
        self.employee_citizenship = QLabel(self.frame_header)
        self.employee_citizenship.setObjectName(u"employee_citizenship")
        self.employee_citizenship.setGeometry(QRect(20, 460, 341, 31))
        self.employee_citizenship.setFont(font6)
        self.civ_status_header = QLabel(self.frame_header)
        self.civ_status_header.setObjectName(u"civ_status_header")
        self.civ_status_header.setGeometry(QRect(20, 490, 161, 21))
        self.civ_status_header.setFont(font5)
        self.employee_civil_status = QLabel(self.frame_header)
        self.employee_civil_status.setObjectName(u"employee_civil_status")
        self.employee_civil_status.setGeometry(QRect(20, 510, 341, 31))
        self.employee_civil_status.setFont(font6)
        self.spouse_header = QLabel(self.frame_header)
        self.spouse_header.setObjectName(u"spouse_header")
        self.spouse_header.setGeometry(QRect(20, 540, 161, 21))
        self.spouse_header.setFont(font5)
        self.employee_spouse = QLabel(self.frame_header)
        self.employee_spouse.setObjectName(u"employee_spouse")
        self.employee_spouse.setGeometry(QRect(20, 560, 341, 31))
        self.employee_spouse.setFont(font6)
        self.children_header = QLabel(self.frame_header)
        self.children_header.setObjectName(u"children_header")
        self.children_header.setGeometry(QRect(20, 590, 161, 21))
        self.children_header.setFont(font5)
        self.employee_children = QLabel(self.frame_header)
        self.employee_children.setObjectName(u"employee_children")
        self.employee_children.setGeometry(QRect(20, 610, 341, 31))
        self.employee_children.setFont(font6)
        self.employee_children2 = QLabel(self.frame_header)
        self.employee_children2.setObjectName(u"employee_children2")
        self.employee_children2.setGeometry(QRect(20, 640, 341, 31))
        self.employee_children2.setFont(font6)
        self.father_header = QLabel(self.frame_header)
        self.father_header.setObjectName(u"father_header")
        self.father_header.setGeometry(QRect(380, 220, 161, 21))
        self.father_header.setFont(font5)
        self.mother_header = QLabel(self.frame_header)
        self.mother_header.setObjectName(u"mother_header")
        self.mother_header.setGeometry(QRect(380, 280, 161, 21))
        self.mother_header.setFont(font5)
        self.frame = QFrame(self.frame_header)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(360, 210, 2, 551))
        self.frame.setStyleSheet(u"background-color: black")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.employee_father = QLabel(self.frame_header)
        self.employee_father.setObjectName(u"employee_father")
        self.employee_father.setGeometry(QRect(380, 240, 341, 31))
        self.employee_father.setFont(font6)
        self.employee_mother = QLabel(self.frame_header)
        self.employee_mother.setObjectName(u"employee_mother")
        self.employee_mother.setGeometry(QRect(380, 300, 341, 31))
        self.employee_mother.setFont(font6)
        self.sss_header = QLabel(self.frame_header)
        self.sss_header.setObjectName(u"sss_header")
        self.sss_header.setGeometry(QRect(380, 460, 161, 21))
        self.sss_header.setFont(font5)
        self.employee_sss = QLabel(self.frame_header)
        self.employee_sss.setObjectName(u"employee_sss")
        self.employee_sss.setGeometry(QRect(380, 480, 341, 31))
        self.employee_sss.setFont(font6)
        self.pagibig_header = QLabel(self.frame_header)
        self.pagibig_header.setObjectName(u"pagibig_header")
        self.pagibig_header.setGeometry(QRect(380, 520, 161, 21))
        self.pagibig_header.setFont(font5)
        self.employee_pagibig = QLabel(self.frame_header)
        self.employee_pagibig.setObjectName(u"employee_pagibig")
        self.employee_pagibig.setGeometry(QRect(380, 540, 341, 31))
        self.employee_pagibig.setFont(font6)
        self.ph_header = QLabel(self.frame_header)
        self.ph_header.setObjectName(u"ph_header")
        self.ph_header.setGeometry(QRect(380, 570, 161, 21))
        self.ph_header.setFont(font5)
        self.employee_philHealth = QLabel(self.frame_header)
        self.employee_philHealth.setObjectName(u"employee_philHealth")
        self.employee_philHealth.setGeometry(QRect(380, 590, 341, 31))
        self.employee_philHealth.setFont(font6)
        self.contact_header = QLabel(self.frame_header)
        self.contact_header.setObjectName(u"contact_header")
        self.contact_header.setGeometry(QRect(380, 630, 161, 21))
        self.contact_header.setFont(font5)
        self.employee_phonenumber = QLabel(self.frame_header)
        self.employee_phonenumber.setObjectName(u"employee_phonenumber")
        self.employee_phonenumber.setGeometry(QRect(380, 650, 341, 31))
        self.employee_phonenumber.setFont(font6)
        self.employee_email = QLabel(self.frame_header)
        self.employee_email.setObjectName(u"employee_email")
        self.employee_email.setGeometry(QRect(380, 680, 341, 31))
        self.employee_email.setFont(font6)
        self.frame_2 = QFrame(self.frame_header)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(660, 210, 2, 551))
        self.frame_2.setStyleSheet(u"background-color: black;")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.relation_header = QLabel(self.frame_header)
        self.relation_header.setObjectName(u"relation_header")
        self.relation_header.setGeometry(QRect(680, 210, 291, 21))
        self.relation_header.setFont(font5)
        self.employee_relation = QLabel(self.frame_header)
        self.employee_relation.setObjectName(u"employee_relation")
        self.employee_relation.setGeometry(QRect(680, 230, 341, 31))
        self.employee_relation.setFont(font6)
        self.schoolheader = QLabel(self.frame_header)
        self.schoolheader.setObjectName(u"schoolheader")
        self.schoolheader.setGeometry(QRect(680, 270, 291, 21))
        self.schoolheader.setFont(font5)
        self.employee_schoolrecords = QLabel(self.frame_header)
        self.employee_schoolrecords.setObjectName(u"employee_schoolrecords")
        self.employee_schoolrecords.setGeometry(QRect(680, 300, 341, 31))
        self.employee_schoolrecords.setFont(font6)
        self.employee_schoolrecords_2 = QLabel(self.frame_header)
        self.employee_schoolrecords_2.setObjectName(u"employee_schoolrecords_2")
        self.employee_schoolrecords_2.setGeometry(QRect(680, 330, 341, 31))
        self.employee_schoolrecords_2.setFont(font6)
        self.employee_schoolrecords_3 = QLabel(self.frame_header)
        self.employee_schoolrecords_3.setObjectName(u"employee_schoolrecords_3")
        self.employee_schoolrecords_3.setGeometry(QRect(680, 360, 341, 31))
        self.employee_schoolrecords_3.setFont(font6)
        self.publications_header = QLabel(self.frame_header)
        self.publications_header.setObjectName(u"publications_header")
        self.publications_header.setGeometry(QRect(680, 410, 291, 21))
        self.publications_header.setFont(font5)
        self.employee_publications = QLabel(self.frame_header)
        self.employee_publications.setObjectName(u"employee_publications")
        self.employee_publications.setGeometry(QRect(680, 440, 341, 31))
        self.employee_publications.setFont(font6)
        self.prev_employment_header = QLabel(self.frame_header)
        self.prev_employment_header.setObjectName(u"prev_employment_header")
        self.prev_employment_header.setGeometry(QRect(680, 490, 291, 21))
        self.prev_employment_header.setFont(font5)
        self.emp_prev_employment = QLabel(self.frame_header)
        self.emp_prev_employment.setObjectName(u"emp_prev_employment")
        self.emp_prev_employment.setGeometry(QRect(680, 510, 341, 31))
        self.emp_prev_employment.setFont(font6)
        self.emp_prev_employment_2 = QLabel(self.frame_header)
        self.emp_prev_employment_2.setObjectName(u"emp_prev_employment_2")
        self.emp_prev_employment_2.setGeometry(QRect(680, 540, 341, 31))
        self.emp_prev_employment_2.setFont(font6)
        self.acad_record_header = QLabel(self.frame_header)
        self.acad_record_header.setObjectName(u"acad_record_header")
        self.acad_record_header.setGeometry(QRect(680, 590, 291, 21))
        self.acad_record_header.setFont(font5)
        self.emp_prev_employment_3 = QLabel(self.frame_header)
        self.emp_prev_employment_3.setObjectName(u"emp_prev_employment_3")
        self.emp_prev_employment_3.setGeometry(QRect(680, 610, 341, 31))
        self.emp_prev_employment_3.setFont(font6)
        self.emp_prev_employment_4 = QLabel(self.frame_header)
        self.emp_prev_employment_4.setObjectName(u"emp_prev_employment_4")
        self.emp_prev_employment_4.setGeometry(QRect(680, 640, 401, 31))
        self.emp_prev_employment_4.setFont(font6)
        self.church_header = QLabel(self.frame_header)
        self.church_header.setObjectName(u"church_header")
        self.church_header.setGeometry(QRect(20, 680, 161, 21))
        self.church_header.setFont(font5)
        self.employee_religion = QLabel(self.frame_header)
        self.employee_religion.setObjectName(u"employee_religion")
        self.employee_religion.setGeometry(QRect(20, 710, 321, 31))
        self.employee_religion.setFont(font6)
        self.brother_header = QLabel(self.frame_header)
        self.brother_header.setObjectName(u"brother_header")
        self.brother_header.setGeometry(QRect(380, 340, 161, 21))
        self.brother_header.setFont(font5)
        self.employee_brother = QLabel(self.frame_header)
        self.employee_brother.setObjectName(u"employee_brother")
        self.employee_brother.setGeometry(QRect(380, 360, 271, 31))
        self.employee_brother.setFont(font6)
        self.brother_header_2 = QLabel(self.frame_header)
        self.brother_header_2.setObjectName(u"brother_header_2")
        self.brother_header_2.setGeometry(QRect(380, 400, 161, 21))
        self.brother_header_2.setFont(font5)
        self.employee_sister = QLabel(self.frame_header)
        self.employee_sister.setObjectName(u"employee_sister")
        self.employee_sister.setGeometry(QRect(380, 420, 261, 31))
        self.employee_sister.setFont(font6)
        self.edit_info_button_2 = QPushButton(self.frame_header)
        self.edit_info_button_2.setObjectName(u"edit_info_button_2")
        self.edit_info_button_2.setGeometry(QRect(20, 770, 131, 16))
        self.edit_info_button_2.setStyleSheet(u"border-radius: 5px;\n"
"\n"
"background-color: rgb(50, 50, 50);\n"
"color: white;\n"
"font-weight: bold;\n"
"")
        self.archive_button_3 = QPushButton(self.frame_header)
        self.archive_button_3.setObjectName(u"archive_button_3")
        self.archive_button_3.setGeometry(QRect(170, 770, 101, 16))
        self.archive_button_3.setStyleSheet(u"border-radius: 5px;\n"
"\n"
"background-color: rgb(138, 138, 138);\n"
"color: white;\n"
"font-weight: bold;\n"
"")
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.line.raise_()
        self.label_4.raise_()
        self.home_button.raise_()
        self.logout_button.raise_()
        self.breadcrumb_label.raise_()
        self.home_button_2.raise_()
        self.logout_button_2.raise_()
        self.label_5.raise_()
        self.frame_header.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Dashboard", None))
        self.label.setText("")
        self.label_3.setText("")
        self.label_2.setText("")
        self.label_4.setText("")
        self.home_button.setText("")
        self.logout_button.setText("")
        self.breadcrumb_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt; color:#323232;\">Home / Currently Employed Records/ Juan Dela Cruz</span></p></body></html>", None))
        self.home_button_2.setText("")
        self.logout_button_2.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt; color:#535353;\">Silliman University Personnel Record Dashboard</span></p></body></html>", None))
        self.employee_name.setText(QCoreApplication.translate("MainWindow", u"Juan Dela Cruz", None))
        self.employee_position.setText(QCoreApplication.translate("MainWindow", u"Professor", None))
        self.employee_department.setText(QCoreApplication.translate("MainWindow", u"College of Computer Studies", None))
        self.employee_hired_date.setText(QCoreApplication.translate("MainWindow", u"Employed on 08/06/2024", None))
        self.edit_info_button.setText(QCoreApplication.translate("MainWindow", u"Edit Information", None))
        self.archive_button.setText(QCoreApplication.translate("MainWindow", u"Archive", None))
        self.archive_button_2.setText(QCoreApplication.translate("MainWindow", u"Salary", None))
        self.employee_duma_address_header.setText(QCoreApplication.translate("MainWindow", u"Dumaguete Address", None))
        self.employee_duma_address_data.setText(QCoreApplication.translate("MainWindow", u"1337 purok negros, sta negro, battle bus road", None))
        self.employee_duma_address_province.setText(QCoreApplication.translate("MainWindow", u"Negro Oriental", None))
        self.employee_address_header.setText(QCoreApplication.translate("MainWindow", u"Home Address", None))
        self.employee_address_data.setText(QCoreApplication.translate("MainWindow", u"1337 purok negros, sta negro, battle bus road", None))
        self.employee_address_province.setText(QCoreApplication.translate("MainWindow", u"Negro Oriental", None))
        self.birthday_header.setText(QCoreApplication.translate("MainWindow", u"Date of Birth", None))
        self.employee_birthday.setText(QCoreApplication.translate("MainWindow", u"May 9, 1945", None))
        self.citz_header.setText(QCoreApplication.translate("MainWindow", u"Citizenship", None))
        self.employee_citizenship.setText(QCoreApplication.translate("MainWindow", u"Filipino", None))
        self.civ_status_header.setText(QCoreApplication.translate("MainWindow", u"Civil Status", None))
        self.employee_civil_status.setText(QCoreApplication.translate("MainWindow", u"Married in Dumaguete on May 29, 2013", None))
        self.spouse_header.setText(QCoreApplication.translate("MainWindow", u"Name of Spouse", None))
        self.employee_spouse.setText(QCoreApplication.translate("MainWindow", u"Ada P. Graming", None))
        self.children_header.setText(QCoreApplication.translate("MainWindow", u"Children", None))
        self.employee_children.setText(QCoreApplication.translate("MainWindow", u"Ninja Fortnite", None))
        self.employee_children2.setText(QCoreApplication.translate("MainWindow", u"Saddam Sussein", None))
        self.father_header.setText(QCoreApplication.translate("MainWindow", u"Father", None))
        self.mother_header.setText(QCoreApplication.translate("MainWindow", u"Mother", None))
        self.employee_father.setText(QCoreApplication.translate("MainWindow", u"Juanito D. Ela Cruz", None))
        self.employee_mother.setText(QCoreApplication.translate("MainWindow", u"Juanita D. Ela Cruz", None))
        self.sss_header.setText(QCoreApplication.translate("MainWindow", u"SSS Number", None))
        self.employee_sss.setText(QCoreApplication.translate("MainWindow", u"22-111111-12038", None))
        self.pagibig_header.setText(QCoreApplication.translate("MainWindow", u"Pag-Ibig Number", None))
        self.employee_pagibig.setText(QCoreApplication.translate("MainWindow", u"22-111111-12038", None))
        self.ph_header.setText(QCoreApplication.translate("MainWindow", u"Philhealth Number", None))
        self.employee_philHealth.setText(QCoreApplication.translate("MainWindow", u"22-111111-12038", None))
        self.contact_header.setText(QCoreApplication.translate("MainWindow", u"Contact Information", None))
        self.employee_phonenumber.setText(QCoreApplication.translate("MainWindow", u"0920 1337 420", None))
        self.employee_email.setText(QCoreApplication.translate("MainWindow", u"juandelacruz@su.edu.ph", None))
        self.relation_header.setText(QCoreApplication.translate("MainWindow", u"Related Staff Member(s)", None))
        self.employee_relation.setText(QCoreApplication.translate("MainWindow", u"Juanita D. Ela Cruz, Wife, Professor", None))
        self.schoolheader.setText(QCoreApplication.translate("MainWindow", u"School or College Distinctions", None))
        self.employee_schoolrecords.setText(QCoreApplication.translate("MainWindow", u"DepEd Scholarship", None))
        self.employee_schoolrecords_2.setText(QCoreApplication.translate("MainWindow", u"Highest Honors", None))
        self.employee_schoolrecords_3.setText(QCoreApplication.translate("MainWindow", u"Mas higher pas highest honors lol (1956)", None))
        self.publications_header.setText(QCoreApplication.translate("MainWindow", u"School or College Distinctions", None))
        self.employee_publications.setText(QCoreApplication.translate("MainWindow", u"Touch Deprived: A statistical analysis", None))
        self.prev_employment_header.setText(QCoreApplication.translate("MainWindow", u"Record of Previous Employment", None))
        self.emp_prev_employment.setText(QCoreApplication.translate("MainWindow", u"University of Duma (2013)", None))
        self.emp_prev_employment_2.setText(QCoreApplication.translate("MainWindow", u"University of Get E (1999)", None))
        self.acad_record_header.setText(QCoreApplication.translate("MainWindow", u"Academic Record", None))
        self.emp_prev_employment_3.setText(QCoreApplication.translate("MainWindow", u"DepEd Scholarship (1999)", None))
        self.emp_prev_employment_4.setText(QCoreApplication.translate("MainWindow", u"College of Engineering Graduate @ Eng School (2003)", None))
        self.church_header.setText(QCoreApplication.translate("MainWindow", u"Church Affiliation", None))
        self.employee_religion.setText(QCoreApplication.translate("MainWindow", u"Church of Pickle Rick", None))
        self.brother_header.setText(QCoreApplication.translate("MainWindow", u"Brother", None))
        self.employee_brother.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.brother_header_2.setText(QCoreApplication.translate("MainWindow", u"Sister", None))
        self.employee_sister.setText(QCoreApplication.translate("MainWindow", u"Juanita Bata Version D. Ela Cruz", None))
        self.edit_info_button_2.setText(QCoreApplication.translate("MainWindow", u"Edit Information", None))
        self.archive_button_3.setText(QCoreApplication.translate("MainWindow", u"Archive", None))
    # retranslateUi

