CREATE TABLE USER
(
    USER_ID TEXT NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE USER_PROFILE
(
    PROFILE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID TEXT NOT NULL,
    BIO TEXT,
    PROFILE_PICTURE TEXT,
    JOINED_DATE DATE NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);


